# restrict analysis to Germany:
'germany': True
# time period by which aggregating the data:
'time': 'month'
# correlation test and regression plot variables:
'x': 'new_vaccinations'
'y': 'deaths_over_cases'